--(a)
INSERT INTO PRODUCS (ID,NAME,PRICE)
VALUES (1, 'bamba', 9.90 );
INSERT INTO PRODUCS (ID,NAME,PRICE)
VALUES (2, 'cheetos', 14.90 );

--(b)
SELECT * FROM PRODUCS

--(c)
DELETE FROM PRODUCS
WHERE ID = 2

--(d)
UPDATE PRODUCS
SET PRICE = 4.9
WHERE ID = 1
